config/routes.rb
Rails.application.routes.draw do

  get 'address/form'

  resources :sessions, :shoes, :categories
  resources :addresses
  resources :charges

  resources :users do
    member do
      get :confirm_email
      get :upgrade
    end
  end
  get '/admin/users/upgrade' => 'users#upgrade'

  resources :admin, :only => [:index, :shoes, :users, :shoeCreate]
  get '/admin/users' => 'admin#users'
  get '/admin/shoes' => 'admin#shoes'
  get '/admin/shoes/create' => 'admin#shoeCreate'

  resources :carts, :only => [:show, :addresses, :payment]
  get '/cart/addresses' => 'carts#addresses'
  get '/cart/payment' => 'carts#payment'
  get 'cart' => 'carts#show'

  resources :order_items, only: [:create, :update, :destroy]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/' => 'shoes#index'
  post '/shoes/:id' => 'order_items#create'


  get '/address/new' => 'addresses#new'
  get '/addresses' => 'addresses#index'

  root to: 'shoes#index'

end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :user
    belongs_to :country
    belongs_to :addressType, optional: true
end

app/models/address_type.rb
class AddressType < ApplicationRecord
    has_many :addresses, dependent: :destroy
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :shoes, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :shoes, dependent: :destroy
end

app/models/city.rb
class City < ApplicationRecord
    belongs_to :country
    has_many :addresses, dependent: :destroy
end

app/models/color.rb
class Color < ApplicationRecord
    has_many :shoes, dependent: :destroy
end

app/models/country.rb
class Country < ApplicationRecord
    has_many :cities, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  belongs_to :user
  has_many :order_items, dependent: :destroy

  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.price) : 0 }.sum
  end
private

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :shoe
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :size, presence: true

  before_save :finalize

  def price
    if persisted?
      self[:price]
    else
      shoe.price
    end
  end

private

  def finalize
    self[:price] = price
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
    has_many :orders, dependent: :destroy
end

app/models/person.rb
class Person < ApplicationRecord
    has_and_belongs_to_many :addresses
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users, dependent: :destroy
end

app/models/shoe.rb
class Shoe < ApplicationRecord
    belongs_to :style
    belongs_to :brand
    belongs_to :color
    belongs_to :category
    has_and_belongs_to_many :shoe_sizes
    has_many :cart_shoe_details
    has_many :carts, through: :cart_shoe_details
    has_many :order_items, dependent: :destroy
end

app/models/shoe_size.rb
class ShoeSize < ApplicationRecord
    has_and_belongs_to_many :shoes

end

app/models/style.rb
class Style < ApplicationRecord
    has_many :shoes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :role
    has_many :orders, dependent: :destroy
    has_many :addresses, dependent: :destroy

    has_secure_password

    before_create { generate_token(:auth_token) }
    before_create :confirmation_token

    def generate_token(column)
        begin
          self[column] = SecureRandom.urlsafe_base64
        end while User.exists?(column => self[column])
    end

    def email_activate
        self.email_confirmed = true
        self.confirm_token = nil
        save!(:validate => false)
    end

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX }, uniqueness: true
    
    validates :password, presence: true, length: { minimum: 8, message: "must be at least 8 characters long" }

    private
    def confirmation_token
        if self.confirm_token.blank?
            self.confirm_token = SecureRandom.urlsafe_base64.to_s
        end
    end
end

app/helpers/admin_helper.rb
module AdminHelper
    def sort_link(column, title = nil)
        title ||= column.titleize
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
        icon = column == sort_column ? icon : ""
        link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
      end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_dashboard.html.erb
<div id="adminDashboard">
    <div class="col-xs-1 adminDashboardItem">
        <%= link_to 'DASHBOARD', '/admin' %>
    </div>
    <div class="col-xs-1 adminDashboardItem">
        <%= link_to 'SHOES', controller: 'admin', action: 'shoes' %>
    </div>
    <div class="col-xs-1 adminDashboardItem">
        <%= link_to 'USERS', '/admin/users' %>
    </div>
</div>

app/views/admin/_index.html.erb

<div id="adminIndex" class="row">
    <div class="col-xs-6">
        <%= link_to 'admin/shoes' do %>
            <div class="adminIndexItem">
                <div class="bubble">
                    <p> <%= @shoes.length %> shoes</p>
                </div>
            </div>
        <% end %>
        <div style="width:85%; margin:0 auto;">
            <%= link_to 'ADD SHOES', '/admin/shoes/create', class: "btn adminButton" %>
        </div>
    </div>
    <div class="col-xs-6">
        <%= link_to 'admin/users' do %>
            <div class="adminIndexItem">
                <div class="bubble">
                    <p> <%= @users.length %> users </p>
                </div>
            </div>
        <% end %>
    </div>
</div>


app/views/admin/_shoeCreateForm.html.erb
<div class="row">
    <div id="shoeCreateForm" class="col-xs-10 col-xs-offset-1">
        <%= form_tag "/shoes", id: "shoeCreateFormForm" do %>
        <div class="row">
            <div class="col-xs-6">
                <br>
                Name:
                <%= text_field_tag 'model', '', class: "form-control" %>
                <br>
                Description:
                <%= text_area :description, :text, class: "form-control" %>
                <br>
                Price:
                <%= text_field_tag 'price', '', class: "form-control" %>
                <br>
                Brand:
                <%= select_tag 'brand', options_from_collection_for_select(@brands, "id", "brand"),
                    {id:"shoe-form-select", class: "form-control"} %>
                <br>
                Category:
                <%= select_tag 'category', options_from_collection_for_select(@categories, "id", "category"),
                    {id:"shoe-form-select", class: "form-control"} %>
                <br>
                Style:
                <%= select_tag 'style', options_from_collection_for_select(@styles, "id", "style"),
                    {id:"shoe-form-select", class: "form-control"} %>
                <br>
                Color:
                <%= select_tag 'color', options_from_collection_for_select(@colors, "id", "color"),
                    {id:"shoe-form-select", class: "form-control"} %>
                <br>
                <br>
                
            </div>
            <div class="col-xs-6">
                <br>
                <br>
                <%= image_tag '', size: "250x250", id: "shoeFormImage" %>
                <br>
                <br>
                <br>
                Link to image:
                <%= text_field_tag 'photo_url', '', class: "form-control" %>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <%= submit_tag "Save", class:" cart-button btn cart-button-continue" %>
                <%= link_to "Back", :back, {id: "cart-button-continue1", class:" cart-button btn cart-button-cancel"} %>
            </div>
        </div>
        <% end %>
    </div>
</div>

<script type="text/javascript">

    function validateaddressFunction() {
    $("#shoeCreateFormForm").validate({
      debug: false,
      rules: {
        "model": { required: true },
        "description[text]": { required: true },
        "price": { required: true, pattern: /^(\d+|\d+,\d{1,2})$/ },
        "photo_url": { required: true },
        "brand": { required: true},
        "category": { required: true },
        "style": { required: true },
        "color": { required: true }
            }
          })
        }
  $(document).ready(validateaddressFunction);
  $(document).on('page:load', validateaddressFunction);


  $('#photo_url').on('input',function(e){
    var str = $('#photo_url').val();
    $('#shoeFormImage').attr('src', str);
});
</script>

app/views/admin/_shoesTable.html.erb
<%= link_to 'ADD SHOES', '/admin/shoes/create', class: "btn adminButton" %>
<div style="height: 5px;"></div>
<table id="adminTable" class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= sort_link "id" %></th>
      <th><%= sort_link "model", "Name" %></th>
      <th><%= sort_link "category_id" %></th>
      <th><%= sort_link "brand_id" %></th>
      <th><%= sort_link "style_id" %></th>
      <th><%= sort_link "color_id" %></th>
      <th><%= sort_link "price" %></th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <% @shoes.each do |shoe| %>
      <tr>
        <td><%= shoe.id %></td>
        <td><%= shoe.model %></td>
        <td><%= shoe.category.category %></td>
        <td><%= shoe.brand.brand %></td>
        <td><%= shoe.style.style %></td>
        <td><%= shoe.color.color %></td>
        <td><%= shoe.price %> KM</td>

        <td>
          <%= link_to shoe, method: :delete,  data: { confirm: 'Are you sure you want to delete this shoe?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>

    <% end %>
  </tbody>
</table>

app/views/admin/_usersTable.html.erb
<table id="adminTable" class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= sort_link "id", "ID" %></th>
      <th><%= sort_link "email" %></th>
      <th><%= sort_link "created_at", "Registration Date" %></th>
      <th><%= sort_link "role_id", "Administrator"%></th>
      <th><%= sort_link "email_confirmed", "Activated"%></th>
      <th> Options </th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>

        <td><%= user.created_at.strftime "%B %e, %Y" %></td>

        <% if user.role.role == 'Admin'%>
          <td> Yes </td>
        <% else %>
          <td> No </td>
        <% end %>
        <td><%= user.email_confirmed%> </th>
        
        <td>
          <% if user.role_id == 2 %>
            <%= link_to upgrade_user_path(user.id), data: { confirm: 'Are you sure you want to upgrade this user to adminsitrator?' } do %>
              <span class="glyphicon glyphicon-pencil"></span>
            <% end %>
          <% end %>
          <%= link_to user, method: :delete,  data: { confirm: 'Are you sure you want to delete this user?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <%= render partial: 'dashboard' %>

            <div id="adminDashboardPanel">
                <%= render partial: 'index' %>
            </div>
        </div>
    </div>
</div>


app/views/admin/shoeCreate.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2" >
            <%= render partial: 'dashboard' %>

            <div id="adminDashboardPanel">
                <%= render partial: 'shoeCreateForm' %>
            </div>
        </div>
    </div>
</div>

app/views/admin/shoes.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <%= render partial: 'dashboard' %>

            <div id="adminDashboardPanel">
                <%= render partial: 'shoesTable' %>
            </div>
        </div>
    </div>
</div>

app/views/admin/users.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <%= render partial: 'dashboard' %>

            <div id="adminDashboardPanel">
                <%= render partial: 'usersTable' %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer style="height: 50px">
  <div class="container">
    <div class="row">
      <div class="col-xs-8 col-xs-ofset-2">
        	<p style="font-size: 10px">Copyright &copy Eds Kingdom. All rights reserved. </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="row">
      <div class="col-xs-1 col-xs-offset-1">
        <div class="navbar-header">
          <%= link_to "Eds Kingdom", '/', id: "navbar-brand-main", class: "navbar-brand" %>
        </div>
      </div>
      <div class="col-xs-5">
        <%= Category.find_each do |category| %>
          <div class="navbar-header">
            <%= link_to category.category.upcase, "/categories/#{category.id}", 
              {id: "navCategory"+category.id.to_s, class: "navCategory navbar-brand"} %>
          </div>
        <% end %>
      </div>

      <div class="col-xs-4">

        <span class="pull-right">
          <% if current_user %>
            <div class="navbar-header">
              <p class="navbar-brand navbar-brand-static"> 
                Welcome <%= current_user.email %> 
              </p>
            </div>
            <% if admin_user %>
              <div class="navbar-header">
                <%= link_to "DASHBOARD", '/admin', class: "navbar-brand" %>
              </div>
            <% end %>
            <div class="navbar-header">
              <%= link_to "LOGOUT", '/logout', class: "navbar-brand" %>
            </div>
          <% else %>
            <div class="navbar-header">
              <%= link_to 'LOGIN', '/login', class: "navbar-brand" %>  
            </div>
            <div class="navbar-header">
              <p class="navbar-brand navbar-brand-static"> | </p>
            </div>
            <div class="navbar-header">
              <%= link_to 'REGISTER', '/signup', class: "navbar-brand" %>
            </div>
          <% end %>
          <div class="navbar-header">
            <%= link_to image_tag("shopping-cart.png", size: "18x18"),
                '/cart', class: "navbar-brand" %>
          </div>
        </span>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-116075461-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-116075461-1');
    </script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Eds Kingdom" %></title>
    <link rel="shortcut icon" href="https://cdn2.iconfinder.com/data/icons/sports-6/128/running-512.png"/>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Webshop" %>">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js" %>
  </head>
  <body>
    <div id="header" class="header-style-1">
      <%= render 'layouts/navigation' %>
    </div>
    <div id="body">
      <%= yield %>
    </div>
    <div id="footer">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

<script>
if (!document.getElementById("gallery")) {
    document.getElementById("header").classList.add('header-style-1');
    document.getElementById("header").classList.remove('header-style-2');
  }
  else {
    document.getElementById("header").classList.add('header-style-2');
    document.getElementById("header").classList.remove('header-style-1');
  }

  if (!document.getElementById("categoryContainer")) {
    //document.getElementById("navCategory").classList.remove('navCategorySelected');
  }
  else {
    var s = window.location.href.split('/');
    var current_cat = s[s.length-1]
    document.getElementById("navCategory"+current_cat).classList.add('navCategorySelected');
  }
</script>