config/routes.rb
Rails.application.routes.draw do

  get 'address/form'

  resources :sessions, :shoes, :categories
  resources :addresses
  resources :charges

  resources :users do
    member do
      get :confirm_email
      get :upgrade
    end
  end
  get '/admin/users/upgrade' => 'users#upgrade'

  resources :admin, :only => [:index, :shoes, :users, :shoeCreate]
  get '/admin/users' => 'admin#users'
  get '/admin/shoes' => 'admin#shoes'
  get '/admin/shoes/create' => 'admin#shoeCreate'

  resources :carts, :only => [:show, :addresses, :payment]
  get '/cart/addresses' => 'carts#addresses'
  get '/cart/payment' => 'carts#payment'
  get 'cart' => 'carts#show'

  resources :order_items, only: [:create, :update, :destroy]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/' => 'shoes#index'
  post '/shoes/:id' => 'order_items#create'


  get '/address/new' => 'addresses#new'
  get '/addresses' => 'addresses#index'

  root to: 'shoes#index'

end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :user
    belongs_to :country
    belongs_to :addressType, optional: true
end

app/models/address_type.rb
class AddressType < ApplicationRecord
    has_many :addresses, dependent: :destroy
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :shoes, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :shoes, dependent: :destroy
end

app/models/city.rb
class City < ApplicationRecord
    belongs_to :country
    has_many :addresses, dependent: :destroy
end

app/models/color.rb
class Color < ApplicationRecord
    has_many :shoes, dependent: :destroy
end

app/models/country.rb
class Country < ApplicationRecord
    has_many :cities, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  belongs_to :user
  has_many :order_items, dependent: :destroy

  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.price) : 0 }.sum
  end
private

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :shoe
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :size, presence: true

  before_save :finalize

  def price
    if persisted?
      self[:price]
    else
      shoe.price
    end
  end

private

  def finalize
    self[:price] = price
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
    has_many :orders, dependent: :destroy
end

app/models/person.rb
class Person < ApplicationRecord
    has_and_belongs_to_many :addresses
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users, dependent: :destroy
end

app/models/shoe.rb
class Shoe < ApplicationRecord
    belongs_to :style
    belongs_to :brand
    belongs_to :color
    belongs_to :category
    has_and_belongs_to_many :shoe_sizes
    has_many :cart_shoe_details
    has_many :carts, through: :cart_shoe_details
    has_many :order_items, dependent: :destroy
end

app/models/shoe_size.rb
class ShoeSize < ApplicationRecord
    has_and_belongs_to_many :shoes

end

app/models/style.rb
class Style < ApplicationRecord
    has_many :shoes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :role
    has_many :orders, dependent: :destroy
    has_many :addresses, dependent: :destroy

    has_secure_password

    before_create { generate_token(:auth_token) }
    before_create :confirmation_token

    def generate_token(column)
        begin
          self[column] = SecureRandom.urlsafe_base64
        end while User.exists?(column => self[column])
    end

    def email_activate
        self.email_confirmed = true
        self.confirm_token = nil
        save!(:validate => false)
    end

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX }, uniqueness: true
    
    validates :password, presence: true, length: { minimum: 8, message: "must be at least 8 characters long" }

    private
    def confirmation_token
        if self.confirm_token.blank?
            self.confirm_token = SecureRandom.urlsafe_base64.to_s
        end
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    before_action :authorize

    def show
        @order_items = current_order.order_items
        @delivery_address = Address.new
        @billing_address = Address.new
    end

    def addresses
        @deliveryAddress = current_user.addresses.find_by_address_type_id(1)
        @billingAddress = current_user.addresses.find_by_address_type_id(2)
        @countries = Country.all
    end

    def payment
        @deliveryAddress = current_user.addresses.find_by_address_type_id(1)
        @billingAddress = current_user.addresses.find_by_address_type_id(2)

    end

end

app/helpers/admin_helper.rb
module AdminHelper
    def sort_link(column, title = nil)
        title ||= column.titleize
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
        icon = column == sort_column ? icon : ""
        link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
      end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_formInput.html.erb
<div id="address-form-div">
        
        Name: 
        <%= text_field_tag 'name'+type, '', class: "form-control" %>
        <br>
        Address: 
        <%= text_field_tag 'address'+type, '', class: "form-control" %>
        <br>        
        City: 
        <%= text_field_tag 'city'+type, '', class: "form-control" %>
        <br>
        Region: 
        <%= text_field_tag 'region'+type, '', class: "form-control" %>
        <br>
        Postal code:
        <%= text_field_tag 'zip'+type, '', class: "form-control" %>
        <br>
        Country:
        <%= select_tag 'country'+type, options_from_collection_for_select(Country.all, "id", "country"),
        {id:"shoe-form-select", class: "form-control"} %>
        <br>
        Telephone: 
        <%= text_field_tag 'telephone'+type, '', class: "form-control" %>

</div>

<script>
  function validateaddressFunction() {
    $("#new_address").validate({
      debug: false,
      rules: {
        "address[name]": { required: true },
        "address[city]": { required: true },
        "address[address]": { required: true },
        "address[region]": { required: true },
        "address[zip]": { required: true },
        "address[telephone]": { required: true },
        "address[country_id]": { required: true },
            }
          })
        }
  $(document).ready(validateaddressFunction);
  $(document).on('page:load', validateaddressFunction);
</script>

app/views/carts/_receipt.html.erb

<div id="receipt-step">
    <div id="receipt-cart">
        CART
    </div>
    <div id="receipt-shipment">
        SHIPMENT
    </div>
    <div id="receipt-payment">
        PAYMENT
    </div>
</div>
<div class="progress">
    <div id="cart-progress-bar" class="progress-bar" role="progressbar" aria-valuemin="0" 
        aria-valuemax="100" style="width:25%">
    </div>
</div>

<div id="receipt-price">
    <div id="receipt-header">
        Order
        <p class="receipt-gray-p" style="display:inline"> 
            <%= current_order.order_items.count %> 
            items 
        </p>
    </div>
    
    <div id="receipt-price-up">
        <p class="receipt-gray-p"> Price </p>
        <p> <%= current_order.subtotal %> </p>
        <p class="receipt-gray-p"> Shipment </p>
        <p> <%= current_order.shipping %> KM </p>
    </div>
    <div id="receipt-price-down">
        In total <%= current_order.subtotal + current_order.shipping %> KM
    </div>
</div>




app/views/carts/_shoeList.html.erb
<p style="font-size: 18px; margin-left: 20px"> Your basket </p>
<% @order_items.each do |order_item|%>
    <div class="row order-item">
        <div class="col-xs-5 order-item-photo">
            <%= link_to shoe_path(order_item.shoe) do %>
                <%= image_tag(order_item.shoe.photo_url) %>
            <% end %>
        </div>
        <div class="col-xs-4 order-item-info">
            Model: <%= order_item.shoe.model %> <br>
            Size: <%= order_item.size %> <br>
            Color: <%= order_item.shoe.color.color %> <br>
            ID: <%= order_item.shoe.id %> <br>
        </div>
        <div class="col-xs-3 order-item-price">
            Price: <br>
            <span style="font-size: 18px; color: black"> <%= order_item.price %> </span> <br>
            <br>
            <br>
            <div>
                Quantity
                <%= text_field_tag 'quantity', order_item.quantity, disabled: true, id: "order-item-quantity" %>
            </div>
            <br>
            <span id="order-item-remove"> <%= link_to "Remove", order_item, method: :delete %> </span>
        </div>
    
    </div>
<% end %>

app/views/carts/addresses.html.erb
<div class="container">
    <%= form_tag "/addresses", id: "addressesForm" do %>
    <div class="row">
        <div class="col-xs-5 col-xs-offset-2">
            <div id="cart-main-div">
                <div style="margin-bottom: 150px">
                    <p style="font-size: 18px; margin-bottom: 20px"> Delivery Address </p>

                   
                    <div class="address-form-div">
                            
                            Name: 
                            <%= text_field_tag 'name', @deliveryAddress ? @deliveryAddress.name : '', 
                                class: "form-control" %>
                            <br>
                            Address: 
                            <%= text_field_tag 'address',  @deliveryAddress ? @deliveryAddress.address : '', class: "form-control" %>
                            <br>        
                            City: 
                            <%= text_field_tag 'city',  @deliveryAddress ? @deliveryAddress.city : '', class: "form-control" %>
                            <br>
                            Region: 
                            <%= text_field_tag 'region',  @deliveryAddress ? @deliveryAddress.region : '', class: "form-control" %>
                            <br>
                            Postal code:
                            <%= text_field_tag 'zip',  @deliveryAddress ? @deliveryAddress.zip : '', class: "form-control" %>
                            <br>
                            Country:
                            <%= select_tag 'country', options_from_collection_for_select(@countries, "id", "country", @deliveryAddress ? @deliveryAddress.country_id : 1),
                            {id:"shoe-form-select", class: "form-control"} %>
                            <br>
                            Telephone: 
                            <%= text_field_tag 'telephone',  @deliveryAddress ? @deliveryAddress.telephone : '', class: "form-control" %>

                    </div>

                    <p style="font-size: 18px; margin: 20px; margin-top: 40px "> 
                        Billing Address 
                        <span style="font-size: 14px; margin-left: 20px">
                            <%= check_box_tag 'addressType', 'billing', true, {id: "billing_address_checkbox"} %>    
                            Use delivery address 
                        </span>
                    </p>
                    <div id="billing-address-div" style="display: none">
                        <div class="address-form-div">
                            
                            Name: 
                            <%= text_field_tag 'name2', @billingAddress ? @billingAddress.name : '', class: "form-control" %>
                            <br>
                            Address: 
                            <%= text_field_tag 'address2', @billingAddress ? @billingAddress.address : '', class: "form-control" %>
                            <br>        
                            City: 
                            <%= text_field_tag 'city2', @billingAddress ? @billingAddress.city : '', class: "form-control" %>
                            <br>
                            Region: 
                            <%= text_field_tag 'region2', @billingAddress ? @billingAddress.region : '', class: "form-control" %>
                            <br>
                            Postal code:
                            <%= text_field_tag 'zip2', @billingAddress ? @billingAddress.zip : '', class: "form-control" %>
                            <br>
                            Country:
                            <%= select_tag 'country2', options_from_collection_for_select(@countries, "id", "country", @billingAddress ? @billingAddress.country_id : 1),
                            {id:"shoe-form-select", class: "form-control"} %>
                            <br>
                            Telephone: 
                            <%= text_field_tag 'telephone2', @billingAddress ? @billingAddress.telephone : '', class: "form-control" %>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-3">
            <%= render "receipt" %>
            <div id="cart-buttons-1" class="cart-buttons">

                <%= submit_tag "Continue", class:" cart-button btn cart-button-continue" %>

                <%= link_to "Back", '/cart', {id: "cart-button-continue1", class:" cart-button btn cart-button-cancel"} %>
            </div>
        </div>
    </div>
    <% end %>
</div>

<script type="text/javascript">
  $('#cart-progress-bar').css('width', '70%');

  var checkbox = document.getElementById('billing_address_checkbox');
  checkbox.onchange = function() {
     if(this.checked) {
       $('#billing-address-div').hide();
     } else {
       $('#billing-address-div').show();
     }
  };


    function validateaddressFunction() {
    $("#addressesForm").validate({
      debug: false,
      rules: {
        "name": { required: true },
        "city": { required: true },
        "address": { required: true },
        "region": { required: true },
        "zip": { required: true, digits: true, minlength: 4},
        "telephone": { required: true, digits: true, minlegth: 9 },
        "country": { required: true },
        "name2": { required: true },
        "city2": { required: true },
        "address2": { required: true },
        "region2": { required: true },
        "zip2": { required: true, digits: true, minlength: 4},
        "telephone2": { required: true, digits: true, minlegth: 9},
        "country2": { required: true }
            }
          })
        }
  $(document).ready(validateaddressFunction);
  $(document).on('page:load', validateaddressFunction);
</script>

app/views/carts/form.html.erb
<div style="margin-bottom: 150px">
    <p style="font-size: 18px; margin: 20px"> Delivery Address </p>
    <%= render "formInput", {:type => "delivery"} %>
    <p style="font-size: 18px; margin: 20px; margin-top: 40px "> 
        Billing Address 
        <span style="font-size: 14px; margin-left: 20px">
            <%= check_box_tag 'addressType', 'billing', true, {id: "billing_address_checkbox"} %>    
            Use delivery address 
        </span>
    </p>
    <div id="billing-address-div" style="display: none">
        <%= render "formInput", {:type => "billing"} %>
    </div>
</div>


<script type="text/javascript">
  var checkbox = document.getElementById('billing_address_checkbox');
  var bAddress_div = document.getElementById('billing-address-div');
  checkbox.onchange = function() {
     if(this.checked) {
       bAddress_div.style['display'] = 'none';
     } else {
       bAddress_div.style['display'] = 'block';
     }
  };
</script>

app/views/carts/index.js.erb
$('#cart-main-div').html("<%=escape_javascript render(:template => 'carts/review') %>");
$('#cart-progress-bar').css('width', '100%');
$('#cart-buttons-2').hide();
$('#cart-buttons-3').html("<%=escape_javascript render(:template => 'carts/stripeButtons') %>");

app/views/carts/new.js.erb
$('#cart-main-div').html("<%=escape_javascript render(:template => 'carts/form') %>");
$('#cart-progress-bar').css('width', '70%');
$('#cart-buttons-1').hide();
$('#cart-buttons-2').show();
$('#cart-buttons-3').hide();

app/views/carts/payment.html.erb
<div class="container">
    <div class="row" style="margin-bottom: 150px">
        <div class="col-xs-5 col-xs-offset-2">
            <div id="cart-main-div">
                <p style="font-size: 18px; margin-left: 20px"> Confirmation and payment </p>
                <br>

                <div class="addressReview">
                    <h4> Delivery Address </h4>
                    <p> <%= @deliveryAddress.name %> </p>
                    <p> <%= @deliveryAddress.address %> </p>
                    <p> <%= @deliveryAddress.city %>, <%= @deliveryAddress.region%> <%= @deliveryAddress.zip%></p>
                    <p> <%= @deliveryAddress.country.country %>
                    <p> Phone: <%= @deliveryAddress.telephone %> </p>
                </div>
                <div class="addressReview">
                    <h4> Billing Address </h4>
                    <p> <%= @billingAddress.name %> </p>
                    <p> <%= @billingAddress.address %> </p>
                    <p> <%= @billingAddress.city %>, <%= @billingAddress.region%> <%= @billingAddress.zip%></p>
                    <p> <%= @billingAddress.country.country %>
                    <p> Phone: <%= @billingAddress.telephone %> </p>
                </div>
            </div>
        </div>
        <div class="col-xs-3">
            <%= render "receipt" %>
            <div id="cart-buttons-1" class="cart-buttons">
                <%= form_tag '/charges' do %>
                    <div class="cart-buttons">
                        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                        data-description=""
                        data-email="<%= current_user.email %>"
                        data-amount= "<%= ((current_order.subtotal + current_order.shipping) * 100) %>"
                        data-locale="auto"
                        data-label="PAY <%= (current_order.subtotal + current_order.shipping) %>KM"
                        data-currency="BAM"
                        data-allow-remember-me="false"></script>
                <% end %>
                <%= link_to "Back", '/cart/addresses', {id: "cart-button-continue1", class:" cart-button btn cart-button-cancel"} %>
            </div>
        </div>
    </div>
</div>

<script>
    $('#cart-progress-bar').css('width', '100%');
</script>

app/views/carts/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-5 col-xs-offset-2">
            <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %>"><%= value %></div>
            <% end %>
            <div id="cart-main-div">
                <%= render "shoeList" %>
            </div>
        </div>
        <div class="col-xs-3">
            <%= render "receipt" %>
            <div id="cart-buttons-1" class="cart-buttons">
                <%= link_to "Continue", 'cart/addresses',
                    {id: "cart-button-continue1", class:" cart-button btn cart-button-continue"} %>
            </div>
        </div>
    </div>
</div>

<script>
    if(document.getElementById("cart-button-continue1") && document.getElementsByClassName("order-item").length === 0){
        $("#cart-button-continue1").on('click', function() { return false; });
    }
</script>